[package]
name = "sabiptrace"
version = "0.1.0"
authors = ["Kazuhiro Kobayashi <orihuzakihsayabok@gmail.com>"]
edition = "2021"

[dependencies]
env_logger = "0.6"
log = "0.4"
nalgebra = "0.31.0"
num_cpus = "1.10"
rand = "0.6"
getopts = "0.2"
either = "1.5"
exr = "1.5.2"
